---
- name:     Set hostname to "{{ base_hostname }}"
  ansible.builtin.hostname:
    name: "{{ base_hostname }}"

- name:     Install RPMFusion
  ansible.builtin.dnf:
    name:   "{{ item }}"
    disable_gpg_check: true
    state:  installed
  when: ansible_pkg_mgr != "yum"
  with_items:
    - https://download1.rpmfusion.org/free/el/rpmfusion-free-release-9.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-9.noarch.rpm
  tags:
    - base-packages

- name:     Install default packages
  ansible.builtin.package:
    name: "{{ item }}"
    state:  installed
  with_items:
    - "{{ base_packages }}"
    - "{{ base_additional_packages }}"
  tags:
    - base-packages
  ignore_errors:  true

- name:     Setup open ports
  ansible.builtin.firewalld:
    port:   "{{ item }}"
    state:  enabled
    permanent:  yes
  with_items: "{{ base_firewall_ports }}"

- name:     Enable firewall
  ansible.builtin.service:
    name:   firewalld
    state:  started

- name:     Reload firewall
  ansible.builtin.command:  firewall-cmd --reload

#- import_role: name=robertdebock.bootstrap
#- import_role: name=singleplatform-eng.users
#  tags:
#    - base
#- import_role: name=geerlingguy.repo-epel
#  when: ansible_distribution == 'CentOS'
#- import_role: name=geerlingguy.ntp
#- import_role: name=arillso.logrotate
#  tags:
#    - logrotate

# # TODO: Use caution to bring these settings in, ensure functionality works first
# # then review their configurations
# # TODO: SETTINGS DOES NOT WORK https://repo.ius.io/ius-release-el7.rpm REQUIRED
# #  - linuxhq.ius
# #  - dev-sec.os-hardening
# #  - dev-sec.ssh-hardening
# #  - geerlingguy.nfs
#    - geerlingguy.postfix
