---
- name:     Set hostname to "{{ base_hostname }}"
  hostname:
    name: "{{ base_hostname }}"

- name:     Install default packages
  package:
    name: "{{ item }}"
    state:  installed
  with_items: 
    - "{{ base_packages }}"
    - "{{ base_additional_packages }}"
  tags:
    - base-packages

- name:     Setup open ports
  firewalld:
    port:   "{{ item }}"
    state:  enabled
    permanent:  yes
  with_items: "{{ base_firewall_ports }}"

- name:     Enable firewall
  service:
    name:   firewalld
    state:  started

- name:     Reload firewall
  command:  firewall-cmd --reload

- import_role: name=robertdebock.bootstrap
- import_role: name=singleplatform-eng.users
  tags:
    - base
- import_role: name=geerlingguy.repo-epel
- import_role: name=geerlingguy.ntp
- import_role: name=arillso.logrotate

# # TODO: Use caution to bring these settings in, ensure functionality works first
# # then review their configurations
# # TODO: SETTINGS DOES NOT WORK https://repo.ius.io/ius-release-el7.rpm REQUIRED
# #  - linuxhq.ius
# #  - dev-sec.os-hardening
# #  - dev-sec.ssh-hardening
# #  - geerlingguy.nfs
#    - geerlingguy.postfix
