---
# VMs are not registered via libvirt DHCP yet
- include_role:   name=uoi-io.haproxy
  vars:
    haproxy_frontend: "{{ http_frontend }}"

- name: Restart haproxy straight after haproxy http setup
  command:  systemctl restart haproxy

- include_tasks: include/acme.yml
  loop: "{{ acme_domains }}"
  loop_control:
    loop_var: domain
  tags: acme

- include_role:   name=uoi-io.haproxy
  tags: haproxy
  vars:
    haproxy_frontend: "{{ http_frontend + https_frontend }}"
