---
- import_role:   name=geerlingguy.repo-remi
- import_role:   name=geerlingguy.apache
- import_role:   name=geerlingguy.apache-php-fpm
- import_role:   name=geerlingguy.php
- import_role:   name=geerlingguy.php-versions
- import_role:   name=geerlingguy.php-pgsql
- import_role:   name=jimcircadian-isso
  tags: isso

- name: Created web directories
  file:
    path:   "{{ item.documentroot }}"
    owner:  root
    group:  root
    state:  directory
    mode:   0755
  with_items: "{{ apache_vhosts }}"
