---
- import_role:   name=geerlingguy.apache
  tags: httpd

- name: Created web directories
  file:
    path:   "{{ item.documentroot }}"
    owner:  root
    group:  root
    state:  directory
    mode:   0755
  with_items: "{{ apache_vhosts }}"
