---
- hosts:  data
  tasks:
    - include_tasks:  include/base.yml
    - include_tasks:  include/data.yml
  vars_files:
    - ../environments/all.yml
    - ../environments/data.yml
    - "../environments/{{ env }}/all.yml"
    - "../environments/{{ env }}/data.yml"
    - "../environments/{{ env }}/vault.yml"
