---
- hosts:  laptop
  tasks:
    - fail: msg="OS combination not currently supported ({{ ansible_distribution }} and v{{ ansible_distribution_version }})"
      when: "not ( ansible_distribution == 'Fedora'
               and ansible_distribution_version == '34' )"

    - include_tasks:  include/base.yml
      tags:
        - base

    - name: Set the graphical target up
      ansible.builtin.command: systemctl set-default graphical.target

    - name: Add the flathub flatpak repository remote to the user installation
      become: False
      community.general.flatpak_remote:
        name:   flathub
        state:  present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
      tags:
        - flatpak

    - name: Install flatpak package from flathub for current user
      become: False
      community.general.flatpak:
        name:   "{{ item }}"
        state:  present
        method: user
      with_items:
        - "{{ f34_flatpak_packages }}"
      tags:
        - flatpak

    # TODO: curl -sf https://www.getlektor.com/installer.py | sudo python3

    # TODO: EDITOR=vim
# https://docs.ansible.com/ansible/latest/collections/community/general/flatpak_module.html
  vars_files:
    - ../environments/vars/all.yml
    - "../environments/vars/{{ env }}/all.yml"
 #   - "../environments/vars/{{ env }}/vault.yml"
