---
- hosts:  host
  tasks:
    - include_tasks:  base.yml
    - include_role:   name=libvirtd
      tags: libvirtd

    - blockinfile:
        path:   "/etc/ssl/certs/{{ env }}.pem"
        owner:  root
        group:  root
        mode:   0600
        block:  "{{ vault_ssl_chain }}"
        create: yes
      tags: haproxy

    - include_role:   name=uoi-io.haproxy
      tags: haproxy

  vars_files:
    - ../environments/all.yml
    - ../environments/host.yml
    - "../environments/{{ env }}/all.yml"
    - "../environments/{{ env }}/host.yml"
    - "../environments/{{ env }}/vault.yml"
