---
- hosts:  host
  tasks:
    - include_tasks:  include/base.yml

    - include_role:   name=libvirtd
      tags: libvirtd

    - include_tasks:  include/proxy.yml

  vars_files:
    - ../environments/all.yml
    - ../environments/host.yml
    - "../environments/{{ env }}/all.yml"
    - "../environments/{{ env }}/host.yml"
    - "../environments/{{ env }}/vault.yml"
