---
- hosts:  server
  tasks:
    - debug: msg="hello"
    - include_tasks:  include/base.yml
  vars_files:
    - ../environments/all.yml
    - ../environments/server.yml
    - "../environments/{{ env }}/all.yml"
    - "../environments/{{ env }}/server.yml"
    - "../environments/{{ env }}/vault.yml"
