---
- hosts:  server
  tasks:
    - debug: msg="hello"
    - include_tasks:  include/base.yml
  vars_files:
    - ../environments/all.yml
    - ../environments/data.yml
    - ../environments/web.yml
    - ../environments/proxy.yml
    - "../environments/{{ env }}/all.yml"
    - "../environments/{{ env }}/data.yml"
    - "../environments/{{ env }}/web.yml"
    - "../environments/{{ env }}/proxy.yml"
    - "../environments/{{ env }}/vault.yml"
