---
- hosts:  vps
  tasks:
    - include_tasks:  include/base.yml
      tags:
        - base
        - base-packages
        - logrotate
    - include_tasks:  include/data.yml
      tags:
        - data
    - include_tasks:  include/web.yml
      tags:
        - isso
        - goaccess
        - httpd
        - postfix
        - games
        - flicks
    - include_tasks:  include/proxy.yml
      tags:
        - acme
        - haproxy
  vars_files:
    - ../environments/all.yml
    - ../environments/data.yml
    - ../environments/web.yml
    - ../environments/proxy.yml
    - "../environments/{{ env }}/all.yml"
    - "../environments/{{ env }}/data.yml"
    - "../environments/{{ env }}/web.yml"
    - "../environments/{{ env }}/proxy.yml"
    - "../environments/{{ env }}/vault.yml"
