---
- hosts:  web
  tasks:
    - include_tasks:  include/base.yml
    - include_tasks:  include/web.yml
  vars_files:
    - ../environments/all.yml
    - ../environments/web.yml
    - "../environments/{{ env }}/all.yml"
    - "../environments/{{ env }}/web.yml"
    - "../environments/{{ env }}/vault.yml"
