---
- name: Ensure podman is installed
  ansible.builtin.package:
    name: podman
    state: installed
  with_items:
    - podman

- name: Create the photos user
  ansible.builtin.user:
    name: photos
    create_home: yes

- name: Modify home directory permissions for group
  ansible.builtin.file:
    path: /home/photos/
    mode: 0750

- name: Create directories necessary for librephotos
  ansible.builtin.file:
    path:   "/home/photos/{{ item }}"
    owner:  photos
    group:  photos
    state:  directory
  with_items:
    - data
    - db
    - protected_media
    - logs

- name: Modify data directory permissions for group
  ansible.builtin.file:
    path: /home/photos/data
    mode: g+w

- name: Specify and run the container
  containers.podman.podman_container:
    name: librephotos
    image: docker.io/reallibrephotos/librephotos-unified
    state: started
    restart: true
    state: started
    recreate: true
    ports:
      - "3000:8001"
    volumes:
      - "/home/photos/data:/data"
      - "/home/photos/db:/db"
      - "/home/photos/protected_media:/protected_media"
      - "/home/photos/logs:/logs"
    env:
      SERVE_FRONTEND: true
      DB_BACKEND: "sqlite"

- name: Add users to the photos user group
  ansible.builtin.user:
    append: true
    groups:
      - photos
    name:   "{{ item }}"
  loop:     "{{ photos_user_list }}"
