---
# VMs are not registered via libvirt DHCP yet
# We must set up the http frontend to field requests for the ACME requests
- import_role:   name=uoi-io.haproxy
  vars:
    haproxy_frontend: "{{ http_frontend }}"
  tags: haproxy

- name: Restart haproxy straight after haproxy http setup
  command:  systemctl restart haproxy

- include_tasks: include/acme.yml
  loop: "{{ acme_domains }}"
  loop_control:
    loop_var: domain
  tags: acme

- import_role:   name=uoi-io.haproxy
  tags: haproxy
  vars:
    haproxy_frontend: "{{ http_frontend + https_frontend }}"
  when: acme_domains|length > 0
