---

# See notes in wsgi.md on Desktop
- name: Setting up WSGI user for any applications
  user:
    name: "{{ item.user }}"
  with_items: "{{ wsgi_endpoints }}"
  no_log:   True
  tags:
    - wsgi

- name: Creating virtual environments
  pip:
    name: "{{ item.pip_uri }}"
    virtualenv: "{{ item.path }}/venv"
    virtualenv_command: "/usr/bin/python3.12 -m venv"
    # TODO: use UV to install this if configurable?
  with_items: "{{ wsgi_endpoints }}"
  no_log:   False
  tags:
    - wsgi

- name: Setting up settings file
  template:
    src: wsgi_env_file.j2
    dest: "/home/{{ item.user }}/.env"
    owner: "{{ item.user }}"
    mode: 0600
  with_items: "{{ wsgi_endpoints }}"
  no_log:   True
  tags:
    - wsgi

- name: Setting up endpoints
  template:
    src: wsgi_app_endpoint.py.j2
    dest: "{{ item.path }}/{{ item.name }}.py"
    mode: 0755
  with_items: "{{ wsgi_endpoints }}"
  no_log:   True
  tags:
    - wsgi

- import_role:   name=geerlingguy.apache
  tags:
  - httpd
  - wsgi

- name: Created web directories
  file:
    path:   "{{ item.documentroot }}"
    owner:  "{{ item.documentroot_owner|default('root') }}"
    group:  root
    state:  directory
    mode:   0755
  with_items: "{{ apache_vhosts }}"
  tags:
    - httpd

- name: Ensure SSL is switched off if present (doesn't happen via apache above)
  ansible.builtin.replace:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '^(Listen 443.*)$'
    replace: '# \1'
  tags:
    - httpd
