---
- hosts:  server
  tasks:
    - include_tasks:  include/base.yml

    - file:
        path:   /data
        state:  directory
        owner:  circadian
        group:  circadian
        mode:   '2750'

    - import_role: name=samba
      tags: samba
    - import_role: name=geerlingguy.nfs
      tags: nfs
    - import_role: name=geerlingguy.postgresql
      tags: data
    - import_role: name=geerlingguy.docker
      tags: docker
    - import_role: name=idNoRD.listmonk
      tags: listmonk

    - include_tasks:  include/web.yml
      tags:
        - httpd
        - postfix
    - include_tasks:  include/proxy.yml
      when: proxy_enable
      tags:
        - acme
        - haproxy

  vars_files:
    - ../environments/vars/all.yml
    - ../environments/vars/server.yml
    - "../environments/vars/{{ env }}/all.yml"
    - "../environments/vars/{{ env }}/server.yml"
    - "../environments/vars/{{ env }}/vault.yml"
